version: '3.8'

services:
  app:
    image: ghcr.io/godsizee/lernplattform_v2:latest
    container_name: lerntool_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://Cheffchen:1arschmusik!@db:3306/lerntool_db
      - NEXTAUTH_SECRET=ein_sehr_langes_zufaelliges_geheimnis_fuer_die_verschluesselung_12345
      - NEXTAUTH_URL=http://localhost:3000 # Ersetze dies im Live-Betrieb durch deine Domain (z.B. https://lernplattform.de)
    depends_on:
      - db
    networks:
      - lerntool_network

  db:
    image: mysql:8.0
    container_name: lerntool_db
    restart: always
    environment:
      - MYSQL_DATABASE=lerntool_db
      - MYSQL_USER=Cheffchen
      - MYSQL_PASSWORD=1arschmusik!
      - MYSQL_ROOT_PASSWORD=!!ArschMusik11
    ports:
      - "3306:3306" # Port 3306 für lokale Admin-Tools (z.B. Heidisql oder DBeaver) erreichbar machen
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lerntool_network

volumes:
  db_data:
    driver: local

networks:
  lerntool_network:
    driver: bridge
